### ISSUE TITLE
TDD practice

### ISSUE THREAD

**Issue by John3210of** [showMeTheMoneyPrac/BE_Repo#2]
실전! 스프링 부트와 JPA 활용1 - 웹 애플리케이션 개발 기반으로 코드 작성

branch - TDDTEST1 > 요한,   TDDTEST2 > 승수

**Comment by John3210of** [comment]
TDD 용 branch는 삭제 하지 않고 참고용으로 남겨둘 예정

**Comment by leeseungsoo0701** [comment]
entitiy명: 요한 ~~~1, 승수 ~~~2
같은 DB 앤드 포인트에서 작업하므로 구조에 따라 변할 수 있으므로 따로 설정
