### ISSUE TITLE
https 적용

### ISSUE THREAD

**Issue by John3210of** [showMeTheMoneyPrac/BE_Repo#35]

**Comment by John3210of** [comment]
웹서버 : nginx
ssl : certbot
도메인 : john3210.shop

**Comment by leeseungsoo0701** [comment]
참고 자료: https://velog.io/@jihyunhillpark/2.-spring-boot-%EA%B8%B0%EB%B0%98-%EC%95%B1-%EB%B0%B0%ED%8F%AC-Cerbot-%EC%9D%B8%EC%A6%9D%EC%84%9C-%EB%B0%9C%EA%B8%89%EA%B3%BC-SSL-%EC%A0%81%EC%9A%A9
