### ISSUE TITLE
테스트 커버리지 90퍼센트 이상으로 구성하기

### ISSUE THREAD

**Issue by leeseungsoo0701** [showMeTheMoneyPrac/BE_Repo#68]
![테스트 커버맂](https://user-images.githubusercontent.com/84774696/173729726-1945fad9-f13b-48e5-8c76-5f04683b0d5c.png)

Line을 90퍼 이상으로 맞추기

**Comment by John3210of** [comment]
![image](https://user-images.githubusercontent.com/94155128/174195561-46dfc3b6-2f38-42f0-9055-67b143f9b47d.png)

완료
